<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Async - Await </title>
</head>
<body>
    

    <script>

        function cuadradoPromise(value){
            if(typeof value !== "number") {
                return Promise.reject(`Error, el valor "${value}" ingresado no es número`); 
            }
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve({
                        value,
                        result: value * value
                        });
                    }, 0 | Math.random() * 1000);
                });
            }


    /*Peticiones Asíncronas*/
    async function funcionAsincronaDeclarada(){
        /*Manejo de errores*/
        try {
            console.log("Inicio Async Function"); 
            /*Cada petición puede ser guardada en variables para optimizar más el código*/

            /*await -> Espera el resultado de la ejecución antes de pasar a la siguiente linea y ejecutarla */
            let obj = await cuadradoPromise(0);
            console.log(`Async Function: ${obj.value}, ${obj.result}`);

            obj = await cuadradoPromise(1);
            console.log(`Async Function: ${obj.value}, ${obj.result}`);

            obj = await cuadradoPromise(2);
            console.log(`Async Function: ${obj.value}, ${obj.result}`);

            obj = await cuadradoPromise(3);
            console.log(`Async Function: ${obj.value}, ${obj.result}`);

            obj = await cuadradoPromise(4);
            console.log(`Async Function: ${obj.value}, ${obj.result}`);

            obj = await cuadradoPromise("5");
            console.log(`Async Function: ${obj.value}, ${obj.result}`);

            console.log("Fin Async Function");
        }catch(err){
            console.log(err);     
        }
    }

    funcionAsincronaDeclarada();

    const funcionAsincronaExpresada = async () => {
         /*Manejo de errores*/
         try {
            console.log("Inicio Async Function"); 
        
            let obj = await cuadradoPromise(6);
            console.log(`Async Function: ${obj.value}, ${obj.result}`);

            obj = await cuadradoPromise(7);
            console.log(`Async Function: ${obj.value}, ${obj.result}`);

            obj = await cuadradoPromise(8);
            console.log(`Async Function: ${obj.value}, ${obj.result}`);

            obj = await cuadradoPromise(9);
            console.log(`Async Function: ${obj.value}, ${obj.result}`);

            obj = await cuadradoPromise(10);
            console.log(`Async Function: ${obj.value}, ${obj.result}`);

            obj = await cuadradoPromise(11);
            console.log(`Async Function: ${obj.value}, ${obj.result}`);

            console.log("Fin Async Function");
        }catch(err){
            console.log(err);     
        }
    }

    funcionAsincronaExpresada();
    </script>
</body>
</html>